//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHITIETPHIEUNHAPTHUOC
    {
        public int MaChiTietPhieuNhapThuoc { get; set; }
        public Nullable<int> MaPhieuNhapThuoc { get; set; }
        public Nullable<int> MaCTThuoc { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<int> ThanhTien { get; set; }
    
        public virtual CHITIETTHUOC CHITIETTHUOC { get; set; }
        public virtual PHIEUNHAPTHUOC PHIEUNHAPTHUOC { get; set; }
    }
}
