//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOADON
    {
        public int MaHoaDon { get; set; }
        public Nullable<int> MaPhieuKham { get; set; }
        public Nullable<System.DateTime> NgayKham { get; set; }
        public Nullable<decimal> TienKham { get; set; }
        public Nullable<decimal> TienThuoc { get; set; }
    
        public virtual PHIEUKHAM PHIEUKHAM { get; set; }
    }
}
