//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn
{
    using System;
    using System.Collections.Generic;
    
    public partial class THAMSO
    {
        public int MaTs { get; set; }
        public Nullable<int> SoBenhNhanToiDaTrongNgay { get; set; }
        public Nullable<int> SoLuongLoaiBenh { get; set; }
        public Nullable<int> SoLuongLoaiThuoc { get; set; }
        public Nullable<int> SoLuongDonVi { get; set; }
        public Nullable<int> SoLuongCachDung { get; set; }
        public Nullable<int> TienKham { get; set; }
    }
}
